### ISSUE TITLE
R Package

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-world-marleyhaupt1#2]
Hi Will,

I was overconfident in my ability to create an R package and I didn't visit you during your office hour this week because I thought if I just read the handout and watched the lecture I could figure it out. Alas, the lecture doesn't include your debugging example (with good reason, so that people couldn't copy the answers) and I think I may need a little more instruction. I'm not sure what I need to do to load roxygen2 so I can BUILD and CHECK my package and documentation. Do you have anytime tomorrow or Thursday? I really think it will only take about 15 minutes.

Sorry! I will buy you a delicious cookie!
Marley

**Comment by willpearse** [comment]
That's fine. I'm around after 10 o'clock.

To install `roxygen2` you need just need to run `install.packages("roxygen2")`. I'll show you when I see you.

**Comment by marleyhaupt1** [comment]
Ok sounds good. I have class tomorrow at 10:30, but I will stop by after class around 11:30. Thanks Will! 

Marley

**Comment by marleyhaupt1** [comment]
Hi Will,

 

I’m so sorry to bother you again. I am a TA for Human Physiology Lab and I found out that one of the other TAs is sick and needs me to cover their 11:30 lab today. Is there another time today that would work for you? Maybe sometime between 12:30 and 2:00? I am so sorry!!!

 

Marley
