### ISSUE TITLE
Finishing Up My R Package

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-world-marleyhaupt1#3]
Hi Will,

How do you want me to submit my R package? Do I just need to add the folders (MarleySim, MarleySim.Rcheck, MarleySim_0.1.0.tar.gz) to my github repo? 

Also, I have 1 notes on my R package:
* checking R code for possible problems ... NOTE
init.plants: no visible binding for global variable ‘repro’
Undefined global functions or variables:
  repro

Do I need to be worried about this?
Thanks!
Marley

**Comment by willpearse** [comment]
Just having the R package in your repository is enough; you don't need to
do any more work.

That does look like a problem. It looks like you use the variable
*repro* without
defining it anywhere; perhaps you think it's a function argument and it's
not?

**Comment by marleyhaupt1** [comment]
Huzzah! I fixed the note! I will push my package to github by 2pm today.
Thanks Will
Marley

**Comment by willpearse** [comment]
Great!
